"""add status to reminders

Revision ID: 29b732feb880
Revises: a1b85a830157
Create Date: 2026-04-22 22:22:40.514400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b732feb880'  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = 'a1b85a830157'  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'status')
    # ### end Alembic commands ###
