"""add indexes to notes

Revision ID: 2b5eb936b5d4
Revises: 29b732feb880
Create Date: 2026-04-22 22:28:23.623875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5eb936b5d4'  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = '29b732feb880'  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notes_created_at', 'notes', ['created_at'], unique=False)
    op.create_index('ix_notes_title', 'notes', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_title', table_name='notes')
    op.drop_index('ix_notes_created_at', table_name='notes')
    # ### end Alembic commands ###
